name: Create Matrix Action
description: This action creates a non-square matrix from an input string.

inputs:
  matrix:
    required: true
    description: The matrix string definition.

outputs:
  matrix:
    description: The generated matrix in JSON format.
    value: ${{ steps.create_matrix.outputs.matrix }}

runs:
  using: composite
  steps:

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run matrix creation script
      id: create_matrix
      run: python ${{ github.action_path }}/script.py
      shell: bash
      env:
        INPUT_MATRIX: ${{ inputs.matrix }}

branding:
  icon: grid
  color: purple
